'use strict';
const $ = s => document.querySelector(s);
const menu = $('.menu-toggle');
menu.addEventListener('click', () => { const open=menu.getAttribute('aria-expanded')==='true'; menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Ouvrir la navigation':'Fermer la navigation');$('#mobile-nav').hidden=open; });
$('#mobile-nav').querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('#mobile-nav').hidden=true;}));
const services={
 renovation:{photo:'assets/interior.webp',alt:'Salon contemporain, visuel d’inspiration pour une rénovation',kicker:'LE PROJET DANS SON ENSEMBLE',title:'Une transformation qui a du sens.',text:'Redistribution des espaces, remise à neuf et finitions : les étapes se pensent ensemble, pour un résultat harmonieux et un lieu adapté à vos usages.'},
 amenagement:{photo:'assets/bathroom.webp',alt:'Salle de bain contemporaine, visuel d’inspiration pour un aménagement',kicker:'LES ESPACES AU SERVICE DES USAGES',title:'Faire mieux avec votre espace.',text:'Agencement, pièces d’eau, revêtements et finitions : imaginez des espaces pratiques, agréables et adaptés à votre façon de vivre ou de travailler.'},
 electricite:{photo:'assets/interior.webp',alt:'Intérieur lumineux, visuel d’inspiration pour une réflexion sur l’éclairage',kicker:'LA TECHNIQUE, SIMPLEMENT',title:'Des équipements bien pensés.',text:'Éclairage, prises et équipements électriques : faites le point sur vos besoins et sur les adaptations de l’installation à prévoir dans votre projet.'}
};
const tabs=[...document.querySelectorAll('.service-tab')];
function activate(tab){const s=services[tab.dataset.service];tabs.forEach(t=>{const active=t===tab;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});$('#service-photo').src=s.photo;$('#service-photo').alt=s.alt;$('#service-kicker').textContent=s.kicker;$('#service-title').textContent=s.title;$('#service-description').textContent=s.text;$('#service-panel').setAttribute('aria-labelledby',tab.id);}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key))return;e.preventDefault();let next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+tabs.length)%tabs.length;activate(tabs[next]);tabs[next].focus();});});
const form=$('#project-form');
$('.form-next').addEventListener('click',()=>{const fields=[$('input[name=city]'),$('textarea[name=description]')];if(!fields.every(f=>f.reportValidity()))return;$('#step-one').hidden=true;$('#step-two').hidden=false;$('.form-count').textContent='02 / 02';$('input[name=name]').focus();});
$('.form-back').addEventListener('click',()=>{$('#step-two').hidden=true;$('#step-one').hidden=false;$('.form-count').textContent='01 / 02';$('.form-next').focus();});
document.querySelectorAll('[data-project]').forEach(a=>a.addEventListener('click',()=>{const field=[...form.querySelectorAll('input[name=project]')].find(x=>x.value===a.dataset.project);if(field)field.checked=true;$('#step-two').hidden=true;$('#step-one').hidden=false;$('.form-count').textContent='01 / 02';}));
form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const text=`Bonjour,\n\nJe souhaite échanger sur un projet de ${data.get('project').toLowerCase()} à ${data.get('city')}.\n\n${data.get('description')}\n\nNom : ${data.get('name')}\nE-mail : ${data.get('email')}${data.get('phone')?'\nTéléphone : '+data.get('phone'):''}\n\nBien cordialement,\n${data.get('name')}`;$('#request-preview').textContent=text;$('#mail-link').href='mailto:gilles.singh@cityelec.fr?subject='+encodeURIComponent('Projet de travaux — '+data.get('city'))+'&body='+encodeURIComponent(text);$('#request-dialog').showModal();});
$('.legal-open').addEventListener('click',()=>$('#legal-dialog').showModal());
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close-dialog').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});});
